version: "3.3"

services:

  nandworker:
    image: php:8.1-apache
    container_name: nandworker_c
    volumes:
      - .:/var/www/html
    environment:
      - "APACHE_DOCUMENT_ROOT=var/www/html"
    ports:
      - 9099:80